id=TestModule
name=Center2 TestModule
version=0.4.0
author=Manager Hub
main=net.managerhub.center.testmodule.TestModule
platform=PAPER
center-min-version=0.4.0
center-max-version=0.4.99
minecraft-min-version=1.21.4
minecraft-max-version=1.21.11
