id=TestModule
name=MHCenter2 TestModule
version=1.0.1
author=Manager Hub
main=net.managerhub.center.testmodule.TestModule
platform=PAPER
center-min-version=1.0.1
center-max-version=1.0.1
minecraft-min-version=1.21.4
minecraft-max-version=1.21.11
