id=TestModule
name=Center2 TestModule
version=1.0.0-beta.1
author=Manager Hub
main=net.managerhub.center.testmodule.TestModule
platform=PAPER
center-min-version=1.0.0
center-max-version=1.0.0
minecraft-min-version=1.21.4
minecraft-max-version=1.21.11
