id=VelocityTestModule
name=MHCenter2 Velocity TestModule
version=1.0.1
author=Manager Hub
main=net.managerhub.center.velocitytestmodule.VelocityTestModule
platform=VELOCITY
center-min-version=1.0.1
center-max-version=1.0.1
