id=VelocityTestModule
name=Center2 Velocity TestModule
version=0.4.0
author=Manager Hub
main=net.managerhub.center.velocitytestmodule.VelocityTestModule
platform=VELOCITY
center-min-version=0.4.0
center-max-version=0.4.99
