id=VelocityTestModule
name=Center2 Velocity TestModule
version=1.0.0-beta.1
author=Manager Hub
main=net.managerhub.center.velocitytestmodule.VelocityTestModule
platform=VELOCITY
center-min-version=1.0.0
center-max-version=1.0.0
